org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
org.gradle.project.android.useAndroidX=true
org.gradle.project.android.enableJetifier=false
android.newDsl=false
org.gradle.daemon=false
